Window.SetBackgroundTopColor (0, 0, 0);
Window.SetBackgroundBottomColor (0, 0, 0);
for (i = 0; i < 28; i++)
  image[i] = Image("progress-" + i + ".png");
sprite = Sprite();

sprite.SetX(Window.GetWidth() / 2 - image[0].GetWidth() / 2);
sprite.SetY(Window.GetHeight() / 2 - image[0].GetHeight() / 2);
progress = 0;

fun refresh_callback ()
  {
    sprite.SetImage(image[Math.Int(progress / 2) % 28]);
    progress++;
  }
Plymouth.SetRefreshFunction (refresh_callback);