#!/bin/bash

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

# Set secure permissions for the initramfs if we're configuring
# full-disk-encryption. The initramfs is re-generated later in the
# installation process so we only set the permissions snippet without
# regenerating the initramfs right now:
if [ "$(mount | grep $CHROOT" " | cut -c -16)" = "/dev/mapper/luks" ]; then
    echo "UMASK=0077" > $CHROOT/etc/initramfs-tools/conf.d/initramfs-permissions
fi

echo "Running replace-bootloader..."

echo " * Replacing old bootloader..."
rm $CHROOT/boot/efi/EFI/VCLinux/grubaa64.efi
cp $CHROOT/boot/grub/arm64-efi/core.efi $CHROOT/boot/efi/EFI/VCLinux/grubaa64.efi
